### ISSUE TITLE
 conflict with other plugins

### ISSUE THREAD

**Issue by devildant** [jneilliii/OctoPrint-StatefulSidebar#1]
Hello @jneilliii ,

I detected a compatibility problem with two plugins.

1) my plugin shutdown printer
issue: https://github.com/devildant/OctoPrint-ShutdownPrinter/issues/11.
but this one is caused by your plugin, during the reduction, after refreshing, your plugin duplicate the ID that I use for the sidebar of my plugin.
I can solve the problem on my side, but your plugin should not duplicate the ID.

2) touchUI plugin
the two plugins conflict, if we reduce an element of the sidebar (for example file), it becomes inaccessible when the interface is loaded with touchUI
![image](https://user-images.githubusercontent.com/8700106/50825417-413b9c00-1339-11e9-847e-2e5b5b2efad7.png)

**Comment by jneilliii** [comment]
As stated in the other issue on your repository, the duplicated IDs is due to your plugin's sidebar template.  It doesn't need the wrapping container with the id you specified as OctoPrint's core plugin system will add that as part of the integration of the jinja template.

**Comment by jneilliii** [comment]
I've re-opened the issue for the TouchUI problem.  I'll have to look into that.  As mentioned, this plugin does not duplicate any dom elements, it just toggles class names.  Thanks for adjusting your code to resolve the other problem, again I think that was being done by OctoPrint not this plugin.

For example as a test I installed my SidebarTempGraph plugin.  That div with an id `sidebar_plugin_sidebartempgraph` is created by OctoPrint and not in the plugin's jinja template. Here it is before installing StatefulSidebar.

![image](https://user-images.githubusercontent.com/5249455/50866177-ec1e7b00-1376-11e9-9ce8-fa855eeb98c7.png)

and this is how it loads with the StatefulSidebar plugin installed.

![image](https://user-images.githubusercontent.com/5249455/50866347-a3b38d00-1377-11e9-9ab6-4434491ced6d.png)

If you had expanded the div with class accordion-body of the screenshot below you would have seen the duplicate embedded by your jinja template, which you removed the id, you could have just deleted the div altogether and your plugin would have still worked fine, as it would have bound the knockout stuff to the div that OctoPrint creates.

![image](https://user-images.githubusercontent.com/5249455/50866542-4966fc00-1378-11e9-85bd-5b687aafc754.png)

Unfortunately, I can't find any documentation on OctoPrint's development section that demonstrates this so I hope it makes sense.

**Comment by devildant** [comment]
I actually see that.
I had not seen that before, my fault.
I also understand why the bug is not present without your plugin, without him the plugins sidebar is still visible, so the collapse is not set, but as your plugin save and restore this state "collapse", octoprint do not remove class of  the second id, logical

**Comment by jneilliii** [comment]
I've got a version 0.1.1 branch up that bypasses collapsing now when touchui is loaded and active.  This should resolve the issue you mentioned @devildant.  If you don't mind verifying by installing the plugin from the following url that would be greatly appreciated.  Once confirmed I'll release an official version.

https://github.com/jneilliii/OctoPrint-StatefulSidebar/archive/0.1.1.zip

**Comment by devildant** [comment]
it's good, nice job :)
